/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Ninja.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Ninja.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Ninja" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Ninja_1" geometry={nodes.Ninja_1.geometry} material={materials.Ninja_Main} skeleton={nodes.Ninja_1.skeleton} />
            <skinnedMesh name="Ninja_2" geometry={nodes.Ninja_2.geometry} material={materials.Ninja_Secondary} skeleton={nodes.Ninja_2.skeleton} />
            <skinnedMesh name="Ninja_3" geometry={nodes.Ninja_3.geometry} material={materials.Belt} skeleton={nodes.Ninja_3.skeleton} />
            <skinnedMesh name="Ninja_4" geometry={nodes.Ninja_4.geometry} material={materials.Eye_White} skeleton={nodes.Ninja_4.skeleton} />
            <skinnedMesh name="Ninja_5" geometry={nodes.Ninja_5.geometry} material={materials.Eye_Black} skeleton={nodes.Ninja_5.skeleton} />
            <skinnedMesh name="Ninja_6" geometry={nodes.Ninja_6.geometry} material={materials.Gold} skeleton={nodes.Ninja_6.skeleton} />
            <skinnedMesh name="Ninja_7" geometry={nodes.Ninja_7.geometry} material={materials.Birb_Secondary} skeleton={nodes.Ninja_7.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Ninja.gltf')
