/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 JapaneseLamp.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function JapaneseLamp(props) {
  const { nodes, materials } = useGLTF("./MODELS/Lamp/JapaneseLamp.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.mat21} />
    </group>
  );
}

useGLTF.preload("./Models/Lamp/JapaneseLamp.gltf");
