/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cloud.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cloud(props) {
  const { nodes, materials } = useGLTF("./MODELS/Cloud/Cloud.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.clouds_01_Plane.geometry}
        material={materials.FFFFFF}
      />
    </group>
  );
}

useGLTF.preload("./MODELS/Cloud/Cloud.gltf");
