/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Tree.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("./MODELS/Tree/Tree.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.IvoryPalmTree_mesh.geometry}
        material={materials.IvoryCanePalmTree_mat}
      />
    </group>
  );
}

useGLTF.preload("./MODELS/Tree/Tree.gltf");
