/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Bonsai.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bonsai(props) {
  const { nodes, materials } = useGLTF("./MODELS/Bonsai/Bonsai.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bonsai1_1.geometry}
        material={materials.TrunkBonsai1}
      />
      <mesh
        geometry={nodes.Bonsai1_2.geometry}
        material={materials.LeafBonsai1}
      />
      <mesh
        geometry={nodes.Bonsai1_3.geometry}
        material={materials.VaseBonsai1}
      />
      <mesh
        geometry={nodes.Bonsai1_4.geometry}
        material={materials.GroundBonsai1}
      />
    </group>
  );
}

useGLTF.preload("./MODELS/Bonsai/Bonsai.gltf");
