/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Pagoda.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pagoda(props) {
  const { nodes, materials } = useGLTF("./MODELS/Pagoda/Pagoda.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Pagoda_mesh.geometry}
        material={materials.lambert2SG}
      />
    </group>
  );
}

useGLTF.preload("./MODELS/Pagoda/Pagoda.gltf");
